### ISSUE TITLE
TOPページ作成

### ISSUE THREAD

**Issue by papi-tokei** [pyconjp/pycon.jp.2020.ui#13]
- [ ] twitterのリンクをつける
- [ ] 「スポンサーに申し込む」「チケットを購入する」「行動規範」、のマウスホバー時の挙動
- [ ] NEWSの部分に手動でコンテンツを入れ込む
- [ ] Contactの部分のメールアドレスをクリックできる感じに修正
- [ ] NEWSとOverViewの横にアイコンをつける
- [ ] TOPビジュアルの背景の〇をつける
- [ ] チケット購入のCOMING SOONラベルをつける
- [ ] 多言語対応

**Comment by ryo-is** [comment]
対応していくー

**Comment by papi-tokei** [comment]
Close
