### ISSUE TITLE
言語が英語の状態でTOPページの行動規範ボタンを押すと、言語が強制的に日本語になる

### ISSUE THREAD

**Issue by papi-tokei** [pyconjp/pycon.jp.2020.ui#25]

**Comment by dowdiness** [comment]
修正しましたhttps://github.com/pyconjp/pycon.jp.2020.ui/pull/26/commits/ba1d68cb72665aa2f7ea9156075fb10e5eff755d

**Comment by papi-tokei** [comment]
ありがとうございます。
