### ISSUE TITLE
1次公開後の文言修正

### ISSUE THREAD

**Issue by peacock0803sz** [pyconjp/pycon.jp.2020.ui#46]
フッターの`in Tokyo`という文字は不要そうなので消す
該当箇所のコード: https://github.com/pyconjp/pycon.jp.2020.ui/blob/master/components/Domains/Footer/index.vue#L43

```
Takanori Suzuki  11:57
@nishi @yoshida https://pycon.jp/2020/en/ のフッターにある「PyCon JP 2020 in Tokyo」ってイベントの正規名称? in Tokyoなくていいのではって思った(急ぎじゃないです
```

**Comment by papi-tokei** [comment]
Keynote のRich Jonesさんの紹介文の冒頭が Gun.io と Gui.io になっているので、内容を確認して統一する
