### ISSUE TITLE
[データ収集ツール] sessionizeからPyCon JPアカウントで作成したプロポーザルも含めてすべてのタイムテーブルの情報を取得できる

### ISSUE THREAD

**Issue by ftnext** [pyconjp/pycon.jp.2020.ui#97]
sessionizeがマスタになる（スタッフは誰でも更新可能）

**Comment by ftnext** [comment]
## 設計メモ

### プロポーザルの種別

- 公募トーク（公募スピーカーが作成）→`Talk`
- PyCon JPスタッフが作成
  - 招待スピーカーによるトーク（キーノート・招待講演）→`InvitedTalk`（Talkを継承）
  - トークではないコンテンツ→`StaffEnteredContent`（Talkを継承）

PyCon JPスタッフが作成したトークは返り値のJSONで`categoryItems`が空がありうる

InvitedTalkではtalk_formatを上書きする（Keynote, Invited talk(45min), Invited talk(30min)にする）

InvitedTalkでは作成者PyCon JPのプロフィールではなく、登壇者のプロフィールを見せたい
→sessionizeに入力した情報をパースして使うことにした（区切り文字を決めておき、descriptionからprofileを取り出す）

StaffEnteredContentはそもそも登壇者がいないのでprofileが不要

**Comment by papi-tokei** [comment]
ありがとうございました。
解決としてクローズさせて頂きますねー
